openapi: "3.0.2"
info:
  title: Short app
  description: url shortener service
  contact:
    name: Vinicius Zenha <vinicius.zenha@gmail.com>
    email: vinicius.zenha@gmail.com
  version: "1.0"
servers:
  - url: https://short.zenhalab.com
    description: server
  - url: http:localhost:3000
    description: local server
paths:
  /:
    get:
      responses:
        "200":
          description: webapp
  /{rash}:
    get:
      tags:
        - url
      parameters:
        - in: "path"
          name: rash
          example: "a-dasf3@152s"
          required: true
          schema:
            type: "string"
      responses:
        "301":
          description: successful redirect
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  Location:
                    type: "string"
                    example: "https://www.destination.com"
        "307":
          description: failed redirect
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  Location:
                    type: "string"
                    example: "short.com/404"
  /url:
    post:
      tags:
        - url
      description: Create short url entry
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                rash:
                  type: string
                  example: a-51asd34123gg
                destination:
                  type: string
                  example: https://google.com
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  url:
                    type: string
                    example: https://s.zenhalab.com/a-3am@sdkm2
